apiVersion: v1
data:
    consul_address: "localhost"
    consul_port: "8500"
    consul_scheme: "http"
    consul_ca_file: ""
    consul_cert_file: ""
    consul_key_file: ""
    consul_insecure_skip_verify: "false"
    consul_token: ""
    consul_timeout: "2s"
    consul_container_name: "consul"
    consul_node_selector: "consul=enabled"
    pod_label_selector: ""
    k8s_tag: "kubernetes"
    register_mode: "single"
    register_source: "pod"
kind: ConfigMap
metadata:
    name: kube-consul-register